a <- 5 * (-1)
b <- 5 * -a
c <- b egal a
d <- non c

f <- 0
tant que non c
    f <- f + 1

    si f egal 100
        c <- vrai
    fin
fin

repeter 5 fois dans i
    e <- "ca repete"
    si i egal 1
        arreter
    fin
fin

si faux
    e <- "ca marche"
fin

fonction factorielle <- i
    si i plus petit que 2
        sortir avec 1
    fin
    
    sortir avec i * factorielle(i - 1)
fin

c <- factorielle(10)

z <- "abcdefghijklmnopqrstuvwxyz"
repeter 26 fois dans h
    c <- z#h
fin

a <- [1,25.56,"salut",[5,3,2]]#4 + ["cc"]

pour chaque i dans a faire 
    
fin