name: Stretch
description: Langage de programmation
author: FATIH KILIC, IBRAHIME AHBIB, ELYES BOUNEZOU, SLIM BEN DAALI, GUILLAUME MERCHEZ, SOFIANE TERKI
branding:
  icon: code
  color: yellow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest