add_repositories("xrepo_guillaume https://github.com/GuillaumeMZ/personal-xrepo.git")
add_repositories("xrepo_fatih https://github.com/swordfatih/xmake-repo.git main")

add_requires("pegtl-nocmake", "catch2", "fmt-nocmake")

target("stretch")
	set_languages("c++17")
	set_kind("binary")
	add_includedirs("include/")
	add_files("src/stretch/*.cpp")
	add_files("src/decimal/*.cpp")
	add_files("src/main.cpp")
	add_packages("pegtl-nocmake", "fmt-nocmake")
	add_rules("mode.debug")

target("test")
	set_languages("c++17")
	set_kind("binary")
	add_includedirs("include/")
	add_files("src/stretch/*.cpp")
	add_files("src/decimal/*.cpp")
	add_files("src/tests/*.cpp")
	add_packages("pegtl-nocmake", "fmt-nocmake", "catch2")