name: Stretch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
